services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - library_data:/var/lib/postgresql/data

volumes:
  library_data: