services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - library_data:/var/lib/postgresql/data
    networks:
        - library-network

  library-app:
    build: .
    container_name: library-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://library_postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
    env_file:
      - .env
    ports:
        - "8081:8080"
    networks:
        - library-network

  libretranslate:
    image: libretranslate/libretranslate:v1.7.2
    container_name: libretranslate
    restart: always
    ports:
      - "5000:5000"
    networks:
      - library-network
    volumes:
        - libretranslate_data:/app/translate/models

volumes:
  library_data:
  libretranslate_data:

networks:
  library-network: